service: timebrew-frontend

provider:
  name: aws
  region: us-east-1
  stage: prod

resources:
  Resources:
    # S3 Bucket for hosting (private, accessed via CloudFront only)
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: timebrew-frontend-prod
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

    # Origin Access Control for CloudFront
    OriginAccessControl:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: "timebrew-s3-oac"
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

    # CloudFront Distribution
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ""
              OriginAccessControlId: !Ref OriginAccessControl
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS]
            CachedMethods: [GET, HEAD]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
          Enabled: true
          DefaultRootObject: index.html
          Aliases:
            - timebrew.news
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:526084139141:certificate/44fe89f1-2e02-430c-bd0e-aa6535273a1d
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html

    # S3 Bucket Policy for CloudFront OAC access
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: cloudfront.amazonaws.com
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
              Condition:
                StringEquals:
                  "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

    # Route53 Record
    DNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z07120566VA5JCWD7F3R
        Name: timebrew.news
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          HostedZoneId: Z2FDTNDATAQYW2

  Outputs:
    WebsiteBucketName:
      Value: !Ref WebsiteBucket
      Description: "S3 Bucket for website hosting"

    CloudFrontDistributionId:
      Value: !Ref CloudFrontDistribution
      Description: "CloudFront Distribution ID"

    CloudFrontDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Description: "CloudFront Domain Name"

    WebsiteURL:
      Value: "https://timebrew.news"
      Description: "Website URL"
